### ISSUE TITLE
Share SMS and EMAIL Not Working 

### ISSUE THREAD

**Issue by sheggietyn** [react-native-share/react-native-share#1107]
Share Sms and Email not working after setup, when button pressed it says

possible unhandled promise rejection(id:3)

object{

error: No Activity found to  handle intent 

}

**Comment by mikehardy** [comment]
Hi there! With apologies, your issue has exactly as much information (and thus validity) as me saying:

Share Sms and Email working great after setup, when button pressed it says

share result == true

I can't imagine anyone being able to help you with the information you have provided.
If you were to trade places with a hypothetical version of yourself that is being asked for help, imagine what you would need to troubleshoot, then provide that. Versions of everything, execution environment, sample code etc.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by sheggietyn** [comment]
My code for email :


const Email = {
    title: 'Title I added here',
    message:
      'some messages I added here  👇👇👇👇',
    url: 'https://somewebsite.link',
    email: 'email@example.com',
    social: Share.Social.EMAIL,
  };

  const EM = async () => {
    const shareResponse = await Share.shareSingle(Email);
  };

**Comment by mikehardy** [comment]
Is this failing with react-native 0.55 on a blackberry? Or... ?
Please please please consult the minimal reproducible example link and note that *execution environment* - **where you reproduce this** is vital to know, along with versions.
I probably won't have time to respond further, as there hasn't been anything actionable here

**Comment by gshenar** [comment]
I am seeing the same thing on my device. Running on android simulator. RN 0.65.1

Error below:

``` 
WARN  Possible Unhandled Promise Rejection (id: 1):
Object {
  "error": "No Activity found to handle Intent { act=android.intent.action.VIEW dat= flg=0x10000000 (has extras) }",
}
```

**Comment by mikehardy** [comment]
`adb logcat` may have interesting information during the attempt / failure

**Comment by ombogdanJoinToIt** [comment]
same on android 12

**Comment by DiazD** [comment]
Same issue as @gshenar 

Here's what I see from `adb logcat`

> ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat= flg=0x10000000 (has extras)}
System.out: ERROR No Activity found to handle Intent { act=android.intent.action.VIEW dat= flg=0x10000000 (has extras) }
System.out: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= flg=0x10000000 (has extras) }
System.out: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2174)
System.out: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1805)
System.out: 	at android.app.ContextImpl.startActivity(ContextImpl.java:1145)
System.out: 	at android.app.ContextImpl.startActivity(ContextImpl.java:1116)
System.out: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:441)
System.out: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:441)
System.out: 	at cl.json.social.SingleShareIntent.openIntentChooser(SingleShareIntent.java:91)
System.out: 	at cl.json.social.SingleShareIntent.openIntentChooser(SingleShareIntent.java:63)
System.out: 	at cl.json.social.EmailShare.open(EmailShare.java:22)
System.out: 	at cl.json.RNShareModule.shareSingle(RNShareModule.java:179)
System.out: 	at java.lang.reflect.Method.invoke(Native Method)
System.out: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
System.out: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
System.out: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
System.out: 	at android.os.Handler.handleCallback(Handler.java:942)
System.out: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.out: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
System.out: 	at android.os.Looper.loopOnce(Looper.java:226)
System.out: 	at android.os.Looper.loop(Looper.java:313)
System.out: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
System.out: 	at java.lang.Thread.run(Thread.java:1012)
ReactNativeJS: 'error', { error: 'No Activity found to handle Intent { act=android.intent.action.VIEW dat= flg=0x10000000 (has extras) }' }

Device: Android 13
React-Native: 0.63.4
react-native-share: 8.1.0

**Comment by davidwinograd1** [comment]
I'm having the same issue! Any updates?

**Comment by davidwinograd1** [comment]
> I am seeing the same thing on my device. Running on android simulator. RN 0.65.1
> 
> Error below:
> 
> ```
> WARN  Possible Unhandled Promise Rejection (id: 1):
> Object {
>   "error": "No Activity found to handle Intent { act=android.intent.action.VIEW dat= flg=0x10000000 (has extras) }",
> }
> ```

Did you resolve this? @gshenar

**Comment by wonderlul** [comment]
![Screenshot 2023-11-08 at 10 48 08](https://github.com/react-native-share/react-native-share/assets/56554355/d8d93e53-cb7d-45c7-b689-444b1d1f033b)

react-native-share: "^9.4.1"
react-native: "0.71.14"
Xiaomi Mi 10T, Android 12

**Comment by wonderlul** [comment]
Okay, got it:
![Screenshot 2023-11-08 at 11 05 16](https://github.com/react-native-share/react-native-share/assets/56554355/3b8a2ddb-f329-43c9-a5b5-4f1537aa41b8)

Quick workaround is to provide empty string as recipient props.
