### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by ThushalIntervest** [react-native-share/react-native-share#1463]
### Steps to reproduce
1. In Android 14(SDK 34) share function is not working 

### Expected behavior
it should work as previous android versions

### Actual behavior
App crash when call the Share.open

### Environment
- **React Native version**: 0.72.4
- **React Native platform + platform version**: Android 14.0 beta

### react-native-share
**Version**: 9.4.1

```
 One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
2023-09-13 15:07:08.027 16203-17052 System.out              com.test.app              I  java.lang.SecurityException: com.test.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
2023-09-13 15:07:08.027 16203-17052 System.out              com.test.app              I  	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
2023-09-13 15:07:08.027 16203-17052 System.out              com.test.app              I  	at android.os.Parcel.createException(Parcel.java:3041)
2023-09-13 15:07:08.027 16203-17052 System.out              com.test.app             I  	at android.os.Parcel.readException(Parcel.java:3024)
2023-09-13 15:07:08.027 16203-17052 System.out              com.test.app              I  	at android.os.Parcel.readException(Parcel.java:2966)
2023-09-13 15:07:08.027 16203-17052 System.out              com.test.app              I  	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
2023-09-13 15:07:08.027 16203-17052 System.out              com.test.app             I  	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
2023-09-13 15:07:08.028 16203-17052 System.out              com.test.app              I  	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
2023-09-13 15:07:08.028 16203-17052 System.out             com.test.app              I  	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
2023-09-13 15:07:08.028 16203-17052 System.out              com.test.app              I  	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
2023-09-13 15:07:08.028 16203-17052 System.out              com.test.app              I  	at cl.json.social.TargetChosenReceiver.getSharingSenderIntent(TargetChosenReceiver.java:49)
2023-09-13 15:07:08.028 16203-17052 System.out              com.test.app              I  	at cl.json.social.ShareIntent.openIntentChooser(ShareIntent.java:268)
2023-09-13 15:07:08.028 16203-17052 System.out             com.test.app              I  	at cl.json.social.GenericShare.open(GenericShare.java:20)
2023-09-13 15:07:08.028 16203-17052 System.out              com.test.app              I  	at cl.json.RNShareImpl.open(RNShareImpl.java:158)
2023-09-13 15:07:08.028 16203-17052 System.out             com.test.app             I  	at cl.json.RNShare.open(RNShare.java:35)
2023-09-13 15:07:08.028 16203-17052 System.out              com.test.app              I  	at java.lang.reflect.Method.invoke(Native Method)
2023-09-13 15:07:08.029 16203-17052 System.out              com.test.app              I  	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
2023-09-13 15:07:08.029 16203-17052 System.out              com.test.app              I  	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
```

**Comment by AptypTheKing** [comment]
Android 14 need to specify the receiver. You need to patch the lib: 

-        ctx.registerReceiver(mReceiver, new IntentFilter("onConfigurationChanged"));
+        ctx.registerReceiver(mReceiver, new IntentFilter("onConfigurationChanged"), ctx.RECEIVER_NOT_EXPORTED);

**Comment by trilam1409** [comment]
> @AptypTheKing Thank you 🙏 ✅. I also found a solution for this from React native release. [facebook/react-native@177d97d](https://github.com/facebook/react-native/commit/177d97d8ea962bdd4dad8fcf0efb04a307f25000)

It doesn't work for me

**Comment by jsg2021** [comment]
> > @AptypTheKing Thank you 🙏 ✅. I also found a solution for this from React native release. [facebook/react-native@177d97d](https://github.com/facebook/react-native/commit/177d97d8ea962bdd4dad8fcf0efb04a307f25000)
> 
> It doesn't work for me

That exact change won't. It was an example of what to fix in this project.  This line needs updating:
https://github.com/react-native-share/react-native-share/blob/main/android/src/main/java/cl/json/social/TargetChosenReceiver.java#L49

**Comment by jsg2021** [comment]
This fixes it for me:
```diff
--- a/node_modules/react-native-share/android/src/main/java/cl/json/social/TargetChosenReceiver.java
+++ b/node_modules/react-native-share/android/src/main/java/cl/json/social/TargetChosenReceiver.java
@@ -46,7 +46,7 @@ public class TargetChosenReceiver extends BroadcastReceiver {
                 context.unregisterReceiver(sLastRegisteredReceiver);
             }
             sLastRegisteredReceiver = new TargetChosenReceiver();
-            context.registerReceiver(sLastRegisteredReceiver, new IntentFilter(sTargetChosenReceiveAction));
+            context.registerReceiver(sLastRegisteredReceiver, new IntentFilter(sTargetChosenReceiveAction), Context.RECEIVER_EXPORTED);
         }

         Intent intent = new Intent(sTargetChosenReceiveAction);
```

**Comment by pierroo** [comment]
I am on react-native-share 10.0.2 with RN 0.73.4, and this issue still exists on android 14 @MateusAndrade 
![image](https://github.com/react-native-share/react-native-share/assets/17619412/790c3544-213e-47f7-9b22-fbfe926eb637)

what am I missing?

**Comment by GSSPawanKumarSingh** [comment]
facing the same issue in my project as well. What exact config need to be done?.

**Comment by pierroo** [comment]
> facing the same issue in my project as well. What exact config need to be done?.

There isn't any config needed, just make sure to use their latest version that's compatible with android 14.
On the other hand, like myself make sure it's related to this library and not a different one which might trigger the same issue (and also need to be upgraded)

**Comment by jael0x** [comment]
I had the same issue, with the package [react-native-settings](https://github.com/rmrs/react-native-settings) in the RNSettingsModule.java file, but fixed with this patch

`
 diff --git a/node_modules/react-native-settings/android/build.gradle b/node_modules/react-native-settings/android/build.gradle
index 6f8e7d0..f85c9dd 100644
--- a/node_modules/react-native-settings/android/build.gradle
+++ b/node_modules/react-native-settings/android/build.gradle
@@ -1,6 +1,7 @@
 buildscript {
     repositories {
         google()
+        jcenter()
     }
     dependencies {
         classpath 'com.android.tools.build:gradle:1.3.1'
diff --git a/node_modules/react-native-settings/android/src/main/java/io/rumors/reactnativesettings/RNSettingsModule.java b/node_modules/react-native-settings/android/src/main/java/io/rumors/reactnativesettings/RNSettingsModule.java
index b0f44c5..84a017c 100644
--- a/node_modules/react-native-settings/android/src/main/java/io/rumors/reactnativesettings/RNSettingsModule.java
+++ b/node_modules/react-native-settings/android/src/main/java/io/rumors/reactnativesettings/RNSettingsModule.java
@@ -1,6 +1,7 @@
 
 package io.rumors.reactnativesettings;
 
+import android.os.Build;
 import android.provider.Settings;
 import android.content.Intent;
 import android.content.IntentFilter;
@@ -91,7 +92,11 @@ public class RNSettingsModule extends ReactContextBaseJavaModule {
 
   private void registerReceiver(Context reactContext, String filter, BroadcastReceiver receiver) {
     IntentFilter intentFilter = new IntentFilter(filter);
-    reactContext.registerReceiver(receiver, intentFilter);
+    if (Build.VERSION.SDK_INT >= 34 && reactContext.getApplicationInfo().targetSdkVersion >= 34) {
+      reactContext.registerReceiver(receiver, intentFilter, Context.RECEIVER_EXPORTED);
+    } else {
+      reactContext.registerReceiver(receiver, intentFilter);
+    }
   }
 
   private void initReceivers() {
`

**Comment by 1ashishkhanna** [comment]
> I am on react-native-share 10.0.2 with RN 0.73.4, and this issue still exists on android 14 @MateusAndrade ![image](https://private-user-images.githubusercontent.com/17619412/305634039-790c3544-213e-47f7-9b22-fbfe926eb637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzQ4NDksIm5iZiI6MTcxMTYzNDU0OSwicGF0aCI6Ii8xNzYxOTQxMi8zMDU2MzQwMzktNzkwYzM1NDQtMjEzZS00N2Y3LTliMjItZmJmZTkyNmViNjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE0MDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNjA0ZmE5ZTg2MWI1ZTFlN2EzMmIzMDJkNTQ2MzNiZGViYzViMjQ4YWMwNWI3ZGRkNDhjODc4MWU0ZGE1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7uxYjKJUvD5758498f6u-UD9pxw4lPscurmdeYh6Ksg)
> 
> what am I missing?
> 
> EDIT: my bad, apparently it may be due to react-native-iap that's also raising the same issue

same issue i'm facing

**Comment by nabzmohd** [comment]
am still faceing the  i

> I am on react-native-share 10.0.2 with RN 0.73.4, and this issue still exists on android 14 @MateusAndrade ![image](https://private-user-images.githubusercontent.com/17619412/305634039-790c3544-213e-47f7-9b22-fbfe926eb637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzU1MzQsIm5iZiI6MTcxMzQzNTIzNCwicGF0aCI6Ii8xNzYxOTQxMi8zMDU2MzQwMzktNzkwYzM1NDQtMjEzZS00N2Y3LTliMjItZmJmZTkyNmViNjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEwMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MjA3ZWE1YzdhYTcyN2E3YzM0NDg2NWMwMjgwOTdlNjlmMjI1NGUzOTliYzI3MTc3NmQyN2M4NTZmOTllOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DPYFOSBdpx3v8XjoDTmmhIfviLD_wDXTlMEbxW2TRqk)
> 
> what am I missing?
> 
> EDIT: my bad, apparently it may be due to react-native-iap that's also raising the same issue

did you get the solution?

**Comment by johhansantana** [comment]
anyone still having issues? my case is very weird since it only happens when the app is in the play store... I've tried debugging it locally and on physical device but they all work and only show the bug in the play store version.

I'm using version `"react-native-share": "10.2.1"`. I'm also using `"react-native": "0.72.10"` don't know if that has to do something
