### ISSUE TITLE
Can't share instagram video story on Android

### ISSUE THREAD

**Issue by idotalmor** [react-native-share/react-native-share#907]
Hi, I am trying to share a video on Instagram story.
iOS working as expected, but on Android it doesn't work.

```
 const cache = await RNFetchBlob.config({
      fileCache: true,
      appendExt: 'mp4',
    }).fetch('GET', 'https://www.w3schools.com/html/mov_bbb.mp4', {});

    await InstaShare.shareSingle({
      social: InstaShare.Social.INSTAGRAM_STORIES,
      method: InstaShare.InstagramStories.SHARE_BACKGROUND_VIDEO,
      backgroundVideo: cache.path(),
      ...Platform.select({
        android: {
          forceDialog: true,
        },
      }),
    });
```

The error I get on Android - 

2020-11-08 12:35:56.759 17348-20900/com.test I/System.out: SHARE SINGLE METHOD
2020-11-08 12:35:56.759 17348-20900/com.test I/System.out: com.instagram.android
2020-11-08 12:35:56.771 17348-20900/com.test I/System.out: INSTALLED
2020-11-08 12:35:56.771 17348-20900/com.test I/System.out: ERROR Unknown Instagram stories sharing mode: shareBackgroundVideo
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out: java.lang.IllegalStateException: Unknown Instagram stories sharing mode: shareBackgroundVideo
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at cl.json.social.ShareIntent.open(ShareIntent.java:213)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at cl.json.social.SingleShareIntent.open(SingleShareIntent.java:40)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at cl.json.social.InstagramStoriesShare.open(InstagramStoriesShare.java:27)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at cl.json.RNShareModule.shareSingle(RNShareModule.java:158)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at java.lang.reflect.Method.invoke(Native Method)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at android.os.Handler.handleCallback(Handler.java:883)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
2020-11-08 12:35:56.773 17348-20900/com.test I/System.out:     at android.os.Looper.loop(Looper.java:237)
2020-11-08 12:35:56.773 17348-20900/com.test I/System.out:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
2020-11-08 12:35:56.773 17348-20900/com.test I/System.out:     at java.lang.Thread.run(Thread.java:919)

**Comment by kaioduarte** [comment]
@idotalmor besides the fact there is not an Android implementation for video sharing at the moment, you need to pass the path prefixed with `file://` as mentioned in [RNFetchBlob doc](https://github.com/joltup/rn-fetch-blob#download-to-storage-directly).
